name: dog_walking_app
services:
  app:
    build: .
    container_name: server_app
    ports:
      - "8000:8000"
    volumes:
      - dog_walking_app:/app
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  dog_walking_app:
